spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  profiles:
    include: jwt   # application-jwt 에 해당하는 properties 혹은 yml 파일을 읽어올 수 있습니다.


logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug