spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test  #;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create  #배포환경 : none
    properties:
      hibernate:
        format_sql: true
        use-sql-comments: true  #주석 사용 (for easier debugging)
        type.descriptor.sql=trace:  #바인딩 되는 파라미터 값 표시
        default_batch_fetch_size: 1000
    open-in-view: false  #OSIV 끄기

  servlet:
    multipart:
      max-request-size: 5MB  #업로드 파일 크기 총량 제한
      max-file-size: 2MB  #업로드 파일 크기 제한


  profiles:
    include: jwt   #application-jwt 에 해당하는 properties 혹은 yml 파일을 읽어올 수 있습니다.


logging.level:
  org:
    hibernate.SQL: debug  #logger 출력 (spring.jpa.properties.hibernate.show_sql=true 와 기능 동일하지만 show_sql 은 System.out 출력)
    springframework.security: debug

